name: CI

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - run: |
          npm ci --legacy-peer-deps

      - name: Lint
        run: |
          npx biome ci .
