on:
  - push

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "yarn"

      - run: |
          yarn install --frozen-lockfile --immutable

      - name: Lint
        run: |
          yarn biome ci .
